name: Build APK

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Get dependencies
      run: |
        cd yigua_app
        flutter clean
        flutter pub get
    
    - name: Fix build issues
      run: |
        cd yigua_app
        echo "flutter.compileSdkVersion=34" >> android/gradle.properties
        echo "flutter.minSdkVersion=21" >> android/gradle.properties
        echo "flutter.targetSdkVersion=34" >> android/gradle.properties
        
        # Create missing directories
        mkdir -p assets/images
        mkdir -p assets/data
        
        # Create placeholder files
        touch assets/images/.gitkeep
        touch assets/data/.gitkeep
    
    - name: Build APK
      run: |
        cd yigua_app
        flutter build apk --release --no-tree-shake-icons
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: yigua_app/build/app/outputs/flutter-apk/app-release.apk
    
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "yigua_app/build/app/outputs/flutter-apk/app-release.apk"
        tag: v${{ github.run_number }}
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true